#!/bin/sh

# No D-list (standard) and D-list (standard)

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_sim_vs_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_sim_vs_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_mult_sim_vs_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_mult_sim_vs_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_exon_sim_vs_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_exon_sim_vs_kallisto_m.txt --barcodes sim_barcodes.txt &


python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_sim_vs_offlist_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_sim_vs_offlist_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_mult_sim_vs_offlist_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_mult_sim_vs_offlist_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_exon_sim_vs_offlist_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_exon_sim_vs_offlist_kallisto_m.txt --barcodes sim_barcodes.txt &


wait

# D-list (standard) overhangs

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_sim_vs_offlistoverhang2_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_sim_vs_offlistoverhang2_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_mult_sim_vs_offlistoverhang2_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_mult_sim_vs_offlistoverhang2_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_exon_sim_vs_offlistoverhang2_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_exon_sim_vs_offlistoverhang2_kallisto_m.txt --barcodes sim_barcodes.txt &


python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_sim_vs_offlistoverhang3_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_sim_vs_offlistoverhang3_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_mult_sim_vs_offlistoverhang3_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_mult_sim_vs_offlistoverhang3_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_exon_sim_vs_offlistoverhang3_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_exon_sim_vs_offlistoverhang3_kallisto_m.txt --barcodes sim_barcodes.txt &

wait

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_sim_vs_offlistoverhang4_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_sim_vs_offlistoverhang4_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_mult_sim_vs_offlistoverhang4_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_mult_sim_vs_offlistoverhang4_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_exon_sim_vs_offlistoverhang4_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_exon_sim_vs_offlistoverhang4_kallisto_m.txt --barcodes sim_barcodes.txt &


python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_sim_vs_offlistoverhang5_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_sim_vs_offlistoverhang5_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_mult_sim_vs_offlistoverhang5_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_mult_sim_vs_offlistoverhang5_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_exon_sim_vs_offlistoverhang5_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_exon_sim_vs_offlistoverhang5_kallisto_m.txt --barcodes sim_barcodes.txt &


python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_sim_vs_offlistoverhang6_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_sim_vs_offlistoverhang6_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_mult_sim_vs_offlistoverhang6_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_mult_sim_vs_offlistoverhang6_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_exon_sim_vs_offlistoverhang6_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.mtx count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/standard_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_exon_sim_vs_offlistoverhang6_kallisto_m.txt --barcodes sim_barcodes.txt &

wait


# No D-list (nac) and D-list (nac)

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_sim_vs_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_sim_vs_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_mult_sim_vs_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_mult_sim_vs_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_exon_sim_vs_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_exon_sim_vs_kallisto_m.txt --barcodes sim_barcodes.txt &


python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_sim_vs_offlist_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_sim_vs_offlist_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_mult_sim_vs_offlist_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_mult_sim_vs_offlist_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_exon_sim_vs_offlist_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlist_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_exon_sim_vs_offlist_kallisto_m.txt --barcodes sim_barcodes.txt &


wait

# D-list (nac) overhangs

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_sim_vs_offlistoverhang2_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_sim_vs_offlistoverhang2_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_mult_sim_vs_offlistoverhang2_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_mult_sim_vs_offlistoverhang2_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_exon_sim_vs_offlistoverhang2_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang2_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_exon_sim_vs_offlistoverhang2_kallisto_m.txt --barcodes sim_barcodes.txt &


python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_sim_vs_offlistoverhang3_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_sim_vs_offlistoverhang3_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_mult_sim_vs_offlistoverhang3_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_mult_sim_vs_offlistoverhang3_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_exon_sim_vs_offlistoverhang3_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang3_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_exon_sim_vs_offlistoverhang3_kallisto_m.txt --barcodes sim_barcodes.txt &

wait

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_sim_vs_offlistoverhang4_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_sim_vs_offlistoverhang4_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_mult_sim_vs_offlistoverhang4_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_mult_sim_vs_offlistoverhang4_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_exon_sim_vs_offlistoverhang4_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang4_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_exon_sim_vs_offlistoverhang4_kallisto_m.txt --barcodes sim_barcodes.txt &


python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_sim_vs_offlistoverhang5_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_sim_vs_offlistoverhang5_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_mult_sim_vs_offlistoverhang5_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_mult_sim_vs_offlistoverhang5_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_exon_sim_vs_offlistoverhang5_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang5_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_exon_sim_vs_offlistoverhang5_kallisto_m.txt --barcodes sim_barcodes.txt &


python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_sim_vs_offlistoverhang6_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_sim_vs_offlistoverhang6_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_mult_sim_vs_offlistoverhang6_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneYes/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_mult_sim_vs_offlistoverhang6_kallisto_m.txt --barcodes sim_barcodes.txt &

python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/default/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_exon_sim_vs_offlistoverhang6_kallisto.txt --barcodes sim_barcodes.txt &
python3 comparisons.py samples/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/truth.mtx genomes/human_CR_3.0.0/genes.tsv data/whitelists/10Xv3 count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.cell.mtx count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.genes.txt count/kallisto_0.50.1/human_CR_3.0.0/nac_offlistoverhang6_1/mult/10X/3/pbmc_5k_sims_human_CR_3.0.0_MultiGeneNo_OnlyExonicReads/20/run1/counts_unfiltered/cells_x_genes.barcodes.txt results/results_nac_exon_sim_vs_offlistoverhang6_kallisto_m.txt --barcodes sim_barcodes.txt &

wait





